option('FWSTATUS_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables firmware status support')

option('PSU_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables PSU support')

option('PSU_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'PSU supported models')

option('FPGA_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables FPGA support')

option('FPGA_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'FPGA supported models')

option('BMC_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'BMC supported models')

option('PCIECHIP_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'PCIE SPI chip supported models')

option('CPLD_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables CPLD support')

option('CPLD_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'CPLD supported models')

option('RT_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables retimer support')

option('GPU_OCP_RECOVERY_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables ocp recovery support')

option('GPU_OCP_RECOVERY_COMPAT_CP2112',
       type: 'feature',
       value: 'disabled',
       description: 'Enables CP2112 I2C transaction compatibility (32B write size)')

option('RT_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'RT supported models')

option('RT_BUSNAME_INVENTORY',
       type: 'string',
       value: '',
       description: 'Service name for RT Inventory Objects')

option('ORIN_FLASH_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables ORIN flash support')

option('SPI_WRITE_PROTECT_APP_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables presence of write protect assert/deassert for Renesas chip')

option('ORIN_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'ORIN supported models')

option('SMCU_FLASH_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables SMCU flash support')

option('SMCU_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'SMCU supported models')

option('SEP_FLASH_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables IGX Safety Extension Package flash support.')

option('SEP_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'IGX Safety Extension Package supported models.')

option('SEP_TIMEOUT',
       type: 'integer',
       value: 1800,
       description: 'IGX Safety Extension Package timeout in seconds.')

option('PEX_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables PEX SW support')

option('PEX_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'PEX supported models')

option('GLACIER_RECOVERY_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables Glacier Recovery support')

option('GLACIER_RECOVERY_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'Glacier Recovery supported models')

option('GLACIER_RECOVERY_TIMEOUT',
       type: 'integer',
       description: 'Glacier Recovery timeout in seconds.')

option('DEBUG_TOKEN_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables Debug Token support')

option('GPU_OCP_RECOVERY_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'OCP Recovery Supported Models')

option('DEBUG_TOKEN_INSTALL_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'Debug Token supported models for install')

option('DEBUG_TOKEN_ERASE_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'Debug Token supported models for erase')

option('MTD_UPDATER_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables MTD update support. It takes 1 min to update fpga and 4 min to update BMC.')

option('SWITCHTEC_FUSE_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables support to be able to set the fuses for switchtec device.')

option('SWITCHTEC_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'SWITCHTEC supported models')

option('JAMPLAYER_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables support to update Altera FPGA over JTAG.')

option('JAMPLAYER_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'Altera supported models')

option('JAMPLAYER_NAME',
       type: 'string',
       value: '',
       description: 'Component target name for JAMPLAYER Inventory Objects')

option('VMEPLAYER_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables support to update Lattice CPLD over JTAG.')

option('VMEPLAYER0_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'Lattice supported models')

option('VMEPLAYER1_SUPPORTED_MODEL',
       type: 'string',
       value: '',
       description: 'Lattice supported models')

option('INVENTORY_PATH_BASE',
       type: 'string',
       value: '/xyz/openbmc_project/inventory/system',
       description: 'The base path for inventory')

option('IMG_DIR',
       type: 'string',
       value: '/tmp/images',
       description: 'The directory where downloaded or uploaded images are placed and extracted')


option('IMG_DIR_PERSIST',
       type: 'string',
       value: '/var/lib/obmc/fwimgs',
       description: 'The writable directory to store updated images persistently')

option('IMG_DIR_BUILTIN',
       type: 'string',
       value: '/usr/share/obmc/fwimgs',
       description: 'The read-only directory where the built-in images are stored')

option(
    'MOCK_UTILS',
    type: 'boolean',
    value: true,
    description: 'Mock underlying hardware calls'
)

option(
    'NON_PLDM_DEFAULT_TIMEOUT',
    type: 'integer',
    value: 1200,
    description: 'Default update timeout in seconds for non PLDM devices.'
)

option(
    'RT_UPDATE_TIMEOUT',
    type: 'integer',
    value: 600,
    description: 'Retimer update timeout in seconds. Default of 600s is computed by: (~1 minute per retimer update * 8 retimers) + (2 minutes for stopping in-progress retimer background hash computation)'
)

option(
    'GPU_OCP_RECOVERY_TIMEOUT',
    type: 'integer',
    description: 'GPU OCP recovery timeout in seconds.'
)

option(
    'MTD_UPDATE_TIMEOUT',
    type: 'integer',
    value: 720,
    description: 'MTD update timeout in seconds.'
)

option(
    'SWITCHTEC_FUSE_TIMEOUT',
    type: 'integer',
    value: 60,
    description: 'Fusing timeout in seconds.'
)

option(
    'JAMPLAYER_TIMEOUT',
    type: 'integer',
    value: 360,
    description: 'jamplayer update timeout in seconds.'
)

option(
    'VMEPLAYER_TIMEOUT',
    type: 'integer',
    value: 360,
    description: 'vmeplayer update timeout in seconds.'
)

option('AP_IMAGE_VERIFICATION',
       type: 'feature',
       value: 'disabled',
       description: 'Enables signature verification support')

option('VERIFY_PCIECHIP',
       type: 'feature',
       value: 'disabled',
       description: 'Enables signature verification of PCIe Chip FW')

option('PUBKEY_PCIECHIP',
       type: 'string',
       value: '',
       description: 'Public Key of PCIe Chip FW')

option('VERIFY_CPLD',
       type: 'feature',
       value: 'disabled',
       description: 'Enables signature verification of CPLD FW')

option('PUBKEY_CPLD',
       type: 'string',
       value: '',
       description: 'Public Key of CPLD FW')

option('VERIFY_JAMPLAYER',
       type: 'feature',
       value: 'disabled',
       description: 'Enables signature verification of JAM files')

option('PUBKEY_JAMPLAYER',
       type: 'string',
       value: '',
       description: 'Public Key of JAM files')

option(
       'tests',
       type: 'feature',
       value: 'enabled',
       description: 'Build tests.'
)

option('MCU_RECOVERY_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables presence of mcu recovery tool in the build')



option('MCU_RECOVERY_SUPPORT',
       type: 'feature',
       value: 'disabled',
       description: 'Enables presence of mcu recovery tool in the build')



option(
       'ENABLE_IN_KERNEL_MCTP',
       type: 'feature',
       value: 'disabled',
       description: 'Use the in-kernel MCTP stack instead of the demux daemon'
)